sudo: required
services:
  - docker
before_install:
  - docker build -t dreamfancy1987/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true dreamfancy1987/react-test npm test
after_success:
  - docker build -t dreamfancy1987/multi-client ./client
  - docker build -t dreamfancy1987/multi-nginx ./nginx
  - docker build -t dreamfancy1987/multi-server ./server
  - docker build -t dreamfancy1987/multi-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin docker.io
  # Take images and push them to docker hub
  - docker push dreamfancy1987/multi-client
  - docker push dreamfancy1987/multi-nginx
  - docker push dreamfancy1987/multi-server
  - docker push dreamfancy1987/multi-worker
deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-745270419650Info'
  bucket_path: 'multi-docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY